# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net


name: .NET React for Ecommerce

env:
  DOTNET_VERSION: '7.0.x'                 # set this to the .NET Core version to use
  NODE-VERSION: '18.x'
  WORKING_DIRECTORY: EcommerceReact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3      
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        
    - name: Restore dependencies
      run: dotnet restore ./EcommerceReact.sln
      
    - name: Install EF Tool
      run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef
            
    - name: Install NPM Dependencies
      run: |
           cd ecommercereact.client
           npm i -f        
          
    - name: Build
      run: dotnet build ./EcommerceReact.sln --configuration Release --no-restore

    - name: Generate scripts
      run: |
           cd EcommerceReact.Server
           dir
           dotnet ef migrations script --output ${{env.WORKING_DIRECTORY}}\sql-script.sql --idempotent --context DataContext --configuration Release --no-build
    #- name: listfiles
    #  run: dir ${{env.WORKING_DIRECTORY}}\
                 
    - name: Test
      run: dotnet test --no-build --verbosity normal

